node {
       stage('Git Glone') {
                    git branch: 'master', credentialsId: 'sujan_git', url: 'https://github.com/bbRemit/mqprocessor'
                    echo '----------------------------- CLONE COMPLETED -----------------------------'
            }

        stage('Maven Build'){
            sh 'mvn clean install'
             echo '----------------------------- MAVEN BUILD COMPLETED -----------------------------'
        }
        stage('Image Build'){
             sh 'docker build -t suzuran1995/mq-processor:1.${BUILD_NUMBER} .'
              echo '----------------------------- IMAGE BUILD COMPLETED -----------------------------'
        }
         stage('Image Push') {
                        withCredentials([string(credentialsId: 'sujan_docker_hub', variable: 'dockerHubPwd')]) {
                            sh "docker login -u suzuran1995 -p ${dockerHubPwd}"
                        }
                            sh 'docker push suzuran1995/mq-processor:1.${BUILD_NUMBER}'
                             echo '----------------------------- IMAGE PUSH COMPLETED -----------------------------'
                }
        stage('Deploy and run'){
             echo '----------------------------- DEPLOY COMPLETED -----------------------------'
        }
  }
